import { labelForPickId } from '../data/sketchPicks'
import { layers, layerOrder } from '../data/layers'
import type { StackSketchState } from '../types'

export function sketchToMarkdown(state: StackSketchState): string {
  const lines: string[] = [
    `# ${state.title}`,
    '',
    '_Draft stack plan from AI Stack Map — layers first; verify vendors and compliance before production._',
    '',
    '## Stack layers',
    '',
  ]

  for (const layerId of layerOrder) {
    if (!state.layers.includes(layerId)) continue
    const layer = layers.find((l) => l.id === layerId)
    const phase = state.phases[layerId] ?? 'mvp'
    const mode = state.modes?.[layerId]
    const pickLabel = labelForPickId(state.picks[layerId])
    const modeLabel = mode ? ` · ${mode.charAt(0).toUpperCase() + mode.slice(1)}` : ''
    lines.push(`### ${layer?.name ?? layerId} (${phase.toUpperCase()}${modeLabel})`)
    lines.push(`- **Choice:** ${pickLabel}`)
    if (mode) lines.push(`- **Approach:** ${mode === 'build' ? 'Build in-house' : mode === 'buy' ? 'Buy / use managed service' : 'Hybrid (part build, part buy)'}`)
    if (layer) lines.push(`- **Skip if:** ${layer.skipIf}`)
    lines.push('')
  }

  if (state.ignore.length > 0) {
    lines.push('## Ignore for now', '')
    for (const item of state.ignore) {
      lines.push(`- ${item}`)
    }
    lines.push('')
  }

  lines.push(
    '---',
    '',
    '_Generated by Stack sketch — not a vendor recommendation._',
    '',
    '## Paste-to-LLM prompt',
    '',
    '> Given the stack above, what are the three highest-risk integration points I should validate before committing to this architecture? For each risk, suggest a concrete spike or proof-of-concept that could de-risk it in a week or less.',
  )
  return lines.join('\n')
}
