import { labelForPickId } from '../data/sketchPicks'
import { layers, layerOrder } from '../data/layers'
import type { StackSketchState } from '../types'

export function sketchToMarkdown(state: StackSketchState): string {
  const lines: string[] = [
    `# ${state.title}`,
    '',
    '_Draft stack plan from AI Stack Map — layers first; verify vendors and compliance before production._',
    '',
    '## Stack layers',
    '',
  ]

  for (const layerId of layerOrder) {
    if (!state.layers.includes(layerId)) continue
    const layer = layers.find((l) => l.id === layerId)
    const phase = state.phases[layerId] ?? 'mvp'
    const pickLabel = labelForPickId(state.picks[layerId])
    lines.push(`### ${layer?.name ?? layerId} (${phase.toUpperCase()})`)
    lines.push(`- **Choice:** ${pickLabel}`)
    if (layer) lines.push(`- **Skip if:** ${layer.skipIf}`)
    lines.push('')
  }

  if (state.ignore.length > 0) {
    lines.push('## Ignore for now', '')
    for (const item of state.ignore) {
      lines.push(`- ${item}`)
    }
    lines.push('')
  }

  lines.push('---', '', '_Generated by Stack sketch — not a vendor recommendation._')
  return lines.join('\n')
}
