import { labelForPickId } from '../data/sketchPicks'
import { layers, layerOrder } from '../data/layers'
import { getSketchHints } from './sketchHints'
import type { StackSketchState } from '../types'

const APPROACH_LABEL = {
  build: 'Build in-house',
  buy: 'Buy / managed service',
  hybrid: 'Hybrid (part build, part buy)',
} as const

function activeLayers(state: StackSketchState) {
  return layerOrder.filter((id) => state.layers.includes(id))
}

export function sketchToMarkdown(state: StackSketchState): string {
  const lines: string[] = [
    `# ${state.title}`,
    '',
    '_Draft stack plan from AI Stack Map — layers first; verify vendors and compliance before production._',
    '',
    '## Stack layers',
    '',
  ]

  for (const layerId of layerOrder) {
    if (!state.layers.includes(layerId)) continue
    const layer = layers.find((l) => l.id === layerId)
    const phase = state.phases[layerId] ?? 'mvp'
    const mode = state.modes?.[layerId]
    const pickLabel = labelForPickId(state.picks[layerId])
    const modeLabel = mode ? ` · ${mode.charAt(0).toUpperCase() + mode.slice(1)}` : ''
    lines.push(`### ${layer?.name ?? layerId} (${phase.toUpperCase()}${modeLabel})`)
    lines.push(`- **Choice:** ${pickLabel}`)
    if (mode) lines.push(`- **Approach:** ${mode === 'build' ? 'Build in-house' : mode === 'buy' ? 'Buy / use managed service' : 'Hybrid (part build, part buy)'}`)
    if (layer) lines.push(`- **Skip if:** ${layer.skipIf}`)
    lines.push('')
  }

  if (state.ignore.length > 0) {
    lines.push('## Ignore for now', '')
    for (const item of state.ignore) {
      lines.push(`- ${item}`)
    }
    lines.push('')
  }

  lines.push(
    '---',
    '',
    '_Generated by Stack sketch — not a vendor recommendation._',
    '',
    '## Paste-to-LLM prompt',
    '',
    '> Given the stack above, what are the three highest-risk integration points I should validate before committing to this architecture? For each risk, suggest a concrete spike or proof-of-concept that could de-risk it in a week or less.',
  )
  return lines.join('\n')
}

/** Architecture Decision Record export — for an engineering design doc or PR. */
export function sketchToADR(state: StackSketchState): string {
  const date = new Date().toISOString().slice(0, 10)
  const lines: string[] = [
    `# ADR: ${state.title}`,
    '',
    '- **Status:** Proposed',
    `- **Date:** ${date}`,
    '',
    '## Context',
    '',
    'We need an AI stack for the goal below. This record captures the layer choices, what we deliberately exclude, and the consequences to manage. Layers first; specific vendors are still to be validated.',
    '',
    '## Decision',
    '',
    'Adopt the following layer-by-layer stack:',
    '',
  ]
  for (const layerId of activeLayers(state)) {
    const layer = layers.find((l) => l.id === layerId)
    const phase = (state.phases[layerId] ?? 'mvp').toUpperCase()
    const mode = state.modes?.[layerId]
    const approach = mode ? ` — ${APPROACH_LABEL[mode]}` : ''
    lines.push(`- **${layer?.name ?? layerId}** (${phase}${approach}): ${labelForPickId(state.picks[layerId])}`)
  }
  lines.push('', '## Alternatives considered / out of scope', '')
  if (state.ignore.length > 0) {
    for (const item of state.ignore) lines.push(`- ${item} — not in this phase`)
  } else {
    lines.push('- _None recorded. Add "Ignore for now" items in the sketch to populate this._')
  }
  lines.push('', '## Consequences', '')
  const hints = getSketchHints(state.layers)
  if (hints.length > 0) {
    for (const h of hints) lines.push(`- ${h.message} — ${h.suggestion}`)
  } else {
    lines.push('- No automated risk flags for this layer combination. Still validate vendors, cost, and compliance.')
  }
  lines.push('', '---', '', '_Generated by AI Stack Map — Stack sketch. Not a vendor recommendation._')
  return lines.join('\n')
}

/** Plain-language summary for non-technical stakeholders ("share with my exec"). */
export function sketchToExecSummary(state: StackSketchState): string {
  const active = activeLayers(state)
  const buildCount = active.filter((id) => state.modes?.[id] === 'build').length
  const buyCount = active.filter((id) => state.modes?.[id] === 'buy').length
  const hybridCount = active.filter((id) => state.modes?.[id] === 'hybrid').length
  const undecided = active.length - buildCount - buyCount - hybridCount
  const lines: string[] = [
    `# ${state.title} — summary for stakeholders`,
    '',
    '## What this is',
    '',
    `A plan for the building blocks of an AI feature, organised into ${active.length} layer${active.length !== 1 ? 's' : ''} of the technology stack. It describes where each piece fits — not a final list of vendors or a budget.`,
    '',
    '## The building blocks',
    '',
  ]
  for (const layerId of active) {
    const layer = layers.find((l) => l.id === layerId)
    const mode = state.modes?.[layerId]
    const approach = mode ? ` _(${APPROACH_LABEL[mode].toLowerCase()})_` : ''
    lines.push(`- **${layer?.name ?? layerId}**${approach}: ${layer?.description ?? ''}`)
  }
  lines.push('')
  if (buildCount || buyCount || hybridCount) {
    lines.push(
      '## Build vs buy',
      '',
      `Current plan across ${active.length} layers: ${buildCount} build, ${buyCount} buy, ${hybridCount} hybrid, ${undecided} undecided.`,
      '',
    )
  }
  if (state.ignore.length > 0) {
    lines.push('## What we are NOT doing yet', '')
    for (const item of state.ignore) lines.push(`- ${item}`)
    lines.push('')
  }
  const hints = getSketchHints(state.layers)
  if (hints.length > 0) {
    lines.push('## Risks to watch', '')
    for (const h of hints) lines.push(`- ${h.message}`)
    lines.push('')
  }
  lines.push('---', '', '_Plain-language export from AI Stack Map. Costs, vendors, and compliance still need validation._')
  return lines.join('\n')
}

/** Risk register export — turns sketch hints + baseline risks into a trackable table. */
export function sketchToRiskRegister(state: StackSketchState): string {
  const hints = getSketchHints(state.layers)
  const rows: string[] = []
  let n = 1
  for (const h of hints) {
    const severity = h.severity === 'warning' ? 'High' : 'Medium'
    rows.push(`| ${n++} | ${h.message} | ${severity} | ${h.suggestion} | _TBD_ |`)
  }
  rows.push(
    `| ${n++} | Vendor lock-in / portability | Medium | Confirm data + prompt export and a fallback provider before committing. | _TBD_ |`,
    `| ${n++} | Cost overrun at scale | Medium | Set spend caps and load-test cost per request before launch. | _TBD_ |`,
    `| ${n++} | Quality regression after a change | Medium | Gate prompt/model changes on an eval set; keep a held-out set. | _TBD_ |`,
  )
  return [
    `# Risk register: ${state.title}`,
    '',
    '_Starter register from AI Stack Map sketch hints plus baseline AI-delivery risks. Severity is a starting point — assign owners and due dates._',
    '',
    '| # | Risk | Severity | Mitigation | Owner |',
    '|---|------|----------|------------|-------|',
    ...rows,
    '',
    '---',
    '',
    '_Generated by AI Stack Map — Stack sketch._',
  ].join('\n')
}
